name: Test git submodules with workflows

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1      
      with:
        python-version: '3.x'
    - name: view files and structure
      run: |
        echo "current directory "
        pwd
        echo "\n"
        cd actions
        echo "current directory "
        pwd
        echo "\n"
    - name: run script on submodule
      run: |
        pwd
        ls
        pip install -r actions/All/requirements.txt
        cd actions/scripts
        python3 gcmd.py
    - name: Commit files
      id: commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions"
        git pull --ff
        git add --all
        if [ -z "$(git status --porcelain)" ]; then
           echo "::set-output name=push::false"
        else
           git commit -m "Add changes" -a
           echo "::set-output name=push::true"
        fi
      shell: bash
    - name: Push changes
      if: steps.commit.outputs.push == 'true'
      uses: ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
        
